// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * 
 */
public class BuildRoadCommand implements PlayerCommand {
	/**
	 * 
	 */
	private int start;
	/**
	 * 
	 */
	private int end;

	public BuildRoadCommand(int start, int end) {
		this.start = start;
		this.end = end;
	}
	/**
	 * 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	public CommandResult execute(Gameplay game, TurnController turnController) {
		Player player = game.getCurrentPlayer();
		Board board = game.getBoard();
		if (board.placeRoad(player, start, end)) {
			System.out.print("Built road at (" + start + ", " + end + ")");
			return new CommandResult(true, false, null);
		}
		System.out.print("Build unsuccessful");
		return null;
	}
}
