// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * 
 */
public class BuildSettlementCommand implements PlayerCommand {
	/**
	 * 
	 */
	private int nodeId;

	public BuildSettlementCommand(int nodeId) {
		this.nodeId = nodeId;
	}

	/**
	 * 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	public CommandResult execute(Gameplay game, TurnController turnController) {
		Player player = game.getCurrentPlayer();
		Board board = game.getBoard();
		if (board.placeSettlement(player, nodeId)) {
			System.out.print("Built settlement at node " + nodeId);
			return new CommandResult(true, false, null);
		}
		System.out.print("Build unsuccessful");
		return null;
	}
}
