// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * 
 */
public class ListStatusCommand implements PlayerCommand {
	/**
	 * 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	public CommandResult execute(Gameplay game, TurnController turnController) {
		Player player = game.getCurrentPlayer();
		Board board = game.getBoard();
		player.printCards(board); //Prints resource cards
		return new CommandResult(true, false, null);
	}
}
