// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/

import java.util.List;

/**
 * 
 */
public class RollDiceCommand implements PlayerCommand {
	/**
	 * 
	 * @param game 
	 * @param turnController 
	 * @return 
	 */
	public CommandResult execute(Gameplay game, TurnController turnController) {
		Player player = game.getCurrentPlayer();
		List<Player> players = game.getPlayers();
		int number = turnController.rollDice();
		turnController.makeResources(number, player, players);
		return new CommandResult(true, false, null);
	}
}
